name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - 
        uses: actions/checkout@v2

      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          registry: docker.pkg.github.com
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - 
        name: Build the Docker image
        env:
            ONEC_USERNAME: ${{ secrets.ONEC_USERNAME }}
            ONEC_PASSWORD: ${{ secrets.ONEC_PASSWORD }}
        run: bash make.sh 'thedemoncat/onec/full'

      - name: Push to GitHub Packages
          uses: docker/build-push-action@v1
          with:
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}
            registry: docker.pkg.github.com
            repository: thedemoncat/onec/full
            tag_with_ref: true



