name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      -
        name: Актуализация
        uses: actions/checkout@v2

      - 
        name: Install buildx
        uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          install: true
      - 
        name: Извлечение версии 1С
        shell: bash
        run: echo "::set-output name=version::$(cat ONEC_VERSION | tail -n1)"
        id: extract_version

      -
        name: Docker Login
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "${GITHUB_TOKEN}" | docker login docker.pkg.github.com --username ${{ github.repository_owner }} --password-stdin 
          docker pull docker.pkg.github.com/thedemoncat/onec-base/onec_base:latest
