name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Build the Docker image
        uses: actions/checkout@v2
        env:
            ONEC_USERNAME: ${{ secrets.ONEC_USERNAME }}
            ONEC_PASSWORD: ${{ secrets.ONEC_PASSWORD }}
        run: bash make.sh



