name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      -
        name: Актуализация
        uses: actions/checkout@v2

      - 
        name: Извлечение версии 1С
        shell: bash
        run: echo "::set-output name=version::$(cat ONEC_VERSION | tail -n1)"
        id: extract_version
      
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      -
        name: Docker Login
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "${GITHUB_TOKEN}" | docker login docker.pkg.github.com --username $GITHUB_ACTOR --password-stdin

      - 
        name: Push to GitHub Packages
        uses: docker/build-push-action@v2
        env: 
          ONEC_VERSION: ${{ steps.extract_version.outputs.version }}
        with:
          context: .
          push: true
          repository: thedemoncat/onec/full
          build-args: |
            ONEC_USERNAME=${{ secrets.ONEC_USERNAME }}
            ONEC_PASSWORD=${{ secrets.ONEC_PASSWORD }}
            ONEC_VERSION=${{ steps.extract_version.outputs.version }}
          tags: |
            docker.pkg.github.com/thedemoncat/onec/full:${{ steps.extract_version.outputs.version }}

